# Site settings
title_short: kÎ²s
title_full: "constant beta software"
email: contact@constantbetasoftware.com
description: > # this means to ignore newlines until "baseurl:"
  Technology.
baseurl: ""
url: "http://constantbetasoftware.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
